# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-01"

[[extensions]]
name = "mit-cards"
handle = "mit-cards"
type = "ui_extension"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension's source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify's storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "card_title"
type = "single_line_text_field"
name = "Card title (English)"
description = "Enter a title for the card in English"

[[extensions.settings.fields]]
key = "card_text"
type = "multi_line_text_field"
name = "Card text (English)"
description = "Enter a text for the card in English"

[[extensions.settings.fields]]
key = "card_title_de"
type = "single_line_text_field"
name = "Card title (German)"
description = "Enter a title for the card in German"

[[extensions.settings.fields]]
key = "card_text_de"
type = "multi_line_text_field"
name = "Card text (German)"
description = "Enter a text for the card in German"

[[extensions.settings.fields]]
key = "card_img_url"
type = "single_line_text_field"
name = "Icon URL (from https://admin.shopify.com/store/frauenschuhshop/content/files)"
description = "Image URL for the card icon (from https://admin.shopify.com/store/frauenschuhshop/content/files)"